spring:
  application:
    name: jwt-practice
  profiles:
    active: local
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.jwt_practice.auth.entity
  configuration:
    map-underscore-to-camel-case: true
jwt:
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs